### ISSUE TITLE
`chalmers @startup` doesn't work on Python 3

### ISSUE THREAD

**Issue by pitrou** [Anaconda-Platform/chalmers#17]
```
C:\Windows\system32>chalmers @startup enable
Your password is required by the windows service manager to launch the chalmers
service at startup
[ERROR]
Traceback (most recent call last):
  File "c:\conda64\Scripts\chalmers-script.py", line 5, in <module>
    sys.exit(chalmers.scripts.chalmers_main.main())
  File "c:\conda64\lib\site-packages\chalmers\scripts\chalmers_main.py", line 36
, in main
    run_command(args, exit=exit)
  File "c:\conda64\lib\site-packages\clyent\__init__.py", line 151, in run_comma
nd
    return args.main(args)
  File "c:\conda64\lib\site-packages\chalmers\commands\at_startup.py", line 50,
in main
    service.install()
  File "c:\conda64\lib\site-packages\chalmers\service\win32_system_service.py",
line 48, in install
    password = getpass.getpass(b"Password for %s: " % self.target_user)
TypeError: %b requires bytes, or an object that implements __bytes__, not 'str'
```

**Comment by srossross** [comment]
thanks @pitrou
